# Generated by Django 5.2.6 on 2025-09-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('phone_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
